### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by bil-ash** [Picsart-AI-Research/Text2Video-Zero#72]
While diffusers work seamlessly on CPU, this model does not. I guess one or more sub-models are hardcoded to use cuda which leads to the problem. Please change that so this model can be run on CPU also. Here is the relevant error
```
Traceback (most recent call last):
  File "/root/difu/Text2Video-Zero/app.py", line 4, in <module>
    from model import Model, ModelType
  File "/root/difu/Text2Video-Zero/model.py", line 11, in <module>
    import utils
  File "/root/difu/Text2Video-Zero/utils.py", line 15, in <module>
    from annotator.midas import MidasDetector
  File "/root/difu/Text2Video-Zero/annotator/midas/__init__.py", line 6, in <module>
    from .api import MiDaSInference
  File "/root/difu/Text2Video-Zero/annotator/midas/api.py", line 9, in <module>
    from .midas.dpt_depth import DPTDepthModel
  File "/root/difu/Text2Video-Zero/annotator/midas/midas/dpt_depth.py", line 6, in <module>
    from .blocks import (
  File "/root/difu/Text2Video-Zero/annotator/midas/midas/blocks.py", line 4, in <module>
    from .vit import (
  File "/root/difu/Text2Video-Zero/annotator/midas/midas/vit.py", line 3, in <module>
    import timm
  File "/usr/local/lib/python3.11/dist-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/usr/local/lib/python3.11/dist-packages/timm/models/__init__.py", line 28, in <module>
    from .maxxvit import *
  File "/usr/local/lib/python3.11/dist-packages/timm/models/maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory
```
Guess the problem is with maxxvit

**Comment by bil-ash** [comment]
Update: managed to get video generation work with CPU. So closing the issue
